name: Audit and Remediate

on:
  workflow_dispatch:
    inputs:
      fcli_version:
        description: fcli version
        required: true
        type: string
        default: 3.17.0
      ssc_version_name:
        description: SSC source version name
        required: true
        type: string
        default: v3

jobs:
  fortify-ast:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      SSC_APPLICATION_NAME: 'petstore'
      SSC_VERSION_NAME: '${{ github.ref_name }}-remediate-${{ github.run_id }}'
      SSC_SOURCE_APPVERSION: 'petstore:${{ inputs.ssc_version_name }}'
      AVIATOR_APP: 'petstore'
    # strategy:
    #   matrix:
    #     java: [ 21 ]
    #     maven: [ '3.8.8' ]

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          # java-version: ${{ matrix.java }}
          java-version: 21
          distribution: temurin

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-# Set up build tool(s) required to build your project

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: ${{ inputs.fcli_version }}
      
      - name: SSC session login
        run: fcli ssc session login --url ${{secrets.SSC_URL}} --token "${{secrets.SSC_TOKEN}}"

      - name: Aviator session login
        run: fcli aviator session login --url ${{vars.AVIATOR_URL}} --token "string:${{secrets.AVIATOR_TOKEN}}"

      - name: Create app version in SSC
        run: fcli ssc appversion create --copy-from "$SSC_SOURCE_APPVERSION" --skip-if-exists "${{ env.SSC_APPLICATION_NAME }}:${{ env.SSC_VERSION_NAME }}"

      - name: Wait for artifact processing
        run: |
          ARTIFACT_ID=$(fcli ssc artifact ls --av "${{ env.SSC_APPLICATION_NAME }}:${{ env.SSC_VERSION_NAME }}" --output json |
            jq -r '
              sort_by(.uploadDate) | 
              last | 
              .id
            ')
          echo "Latest artifact ID: $ARTIFACT_ID"
          fcli ssc artifact wait-for --progress=none $ARTIFACT_ID 

      - name: Aviator audit
        run: fcli aviator ssc audit --av "${{ env.SSC_APPLICATION_NAME }}:${{ env.SSC_VERSION_NAME }}" --app "$AVIATOR_APP"

      - name: Apply remediations
        run: fcli aviator ssc apply-remediations --av "${{ env.SSC_APPLICATION_NAME }}:${{ env.SSC_VERSION_NAME }}" --latest --progress=none

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto-remediation by OpenText SAST Aviator'
          branch: aviator/audit-remediate-${{github.run_id}}
          delete-branch: true
          title: 'Remediation of security issues detected by OpenText SAST'
          body: |
            Remediation of security issues detected by OpenText SAST.
            This PR was automatically created by OpenText SAST Aviator.
            Please review carefully before merging.