name: Scan, Audit and Remediate

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Fortify platform
        required: true
        type: choice
        default: SSC
        options: 
          - SSC
          - FoD
      fcli_version:
        description: fcli version
        required: true
        type: string
        default: 3.17.0

jobs:
  fortify-ast:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      SSC_APPLICATION_NAME: 'petstore'
      FOD_APPLICATION_NAME: 'petstore'
      SSC_VERSION_NAME: '${{ github.ref_name }}-remediate-${{ github.run_id }}'
      FOD_RELEASE_NAME: '${{ github.ref_name }}-remediate-${{ github.run_id }}'
      AVIATOR_APP: 'petstore'
    # strategy:
    #   matrix:
    #     java: [ 21 ]
    #     maven: [ '3.8.8' ]

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          # java-version: ${{ matrix.java }}
          java-version: 21
          distribution: temurin

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-# Set up build tool(s) required to build your project

      - uses: fortify/github-action@v3
        if: ${{ inputs.platform == 'SSC' }}
        env:
          FCLI_BOOTSTRAP_VERSION: v${{ inputs.fcli_version }}

          SSC_URL: ${{ secrets.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_SAST_TOKEN }}
          SSC_LOGIN_EXTRA_OPTS: --sc-sast-url ${{ secrets.SCSAST_URL }}
          SSC_APPVERSION: ${{ format('{0}:{1}', env.SSC_APPLICATION_NAME, env.SSC_VERSION_NAME) }}
          SETUP_EXTRA_OPTS: '--issue-template "Prioritized High Risk Issue Template"' 

          PACKAGE_EXTRA_OPTS: --build-command "--no-transfer-progress"

          DO_APPVERSION_SUMMARY: false
          DO_SAST_EXPORT: false

          DO_AVIATOR_AUDIT: true
          AVIATOR_URL: ${{ vars.AVIATOR_URL }}
          AVIATOR_TOKEN: ${{ secrets.AVIATOR_TOKEN }}
          AVIATOR_APP: ${{ env.AVIATOR_APP }}
          # AVIATOR_AUDIT_EXTRA_OPTS: --folder "Critical,High" --progress=none
          AVIATOR_AUDIT_EXTRA_OPTS: --progress=none


          SSDAST_URL: ${{ secrets.SCDAST_URL }}

      - uses: fortify/github-action@v3
        if: ${{ inputs.platform == 'FoD' }}
        env:
          FCLI_BOOTSTRAP_VERSION: v${{ inputs.fcli_version }}

          FOD_URL: ${{ vars.FOD_URL }}
          FOD_CLIENT_ID: ${{ secrets.FOD_API_KEY }}
          FOD_CLIENT_SECRET: ${{ secrets.FOD_API_SECRET }}
          FOD_RELEASE: ${{ env.FOD_RELEASE }}

          PACKAGE_EXTRA_OPTS: --build-command "--no-transfer-progress"

          DO_RELEASE_SUMMARY: false
          DO_SAST_EXPORT: false

          DO_AVIATOR_AUDIT: true

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: ${{ inputs.fcli_version }}
      
      - name: SSC session login
        if: ${{ inputs.platform == 'SSC' }}
        run: fcli ssc session login --url ${{secrets.SSC_URL}} --token "${{secrets.SSC_TOKEN}}"

      - name: Aviator session login
        if: ${{ inputs.platform == 'SSC' }}
        run: fcli aviator session login --url ${{vars.AVIATOR_URL}} --token "string:${{secrets.AVIATOR_TOKEN}}"

      - name: FoD session login
        if: ${{ inputs.platform == 'FoD' }}
        run: fcli fod session login --url "${{ vars.FOD_URL }}" --client-id "${{ secrets.FOD_API_KEY }}" --client-secret "${{ secrets.FOD_API_SECRET }}"

      - name: Apply remediations (SSC)
        if: ${{ inputs.platform == 'SSC' }}
        run: fcli aviator ssc apply-remediations --av "${{ env.SSC_APPLICATION_NAME }}:${{ env.SSC_VERSION_NAME }}" --latest --progress=none

      - name: Apply remediations (FoD)
        if: ${{ inputs.platform == 'FoD' }}
        run: fcli fod aviator apply-remediations --rel "${{ env.FOD_APPLICATION_NAME }}:${{ env.FOD_RELEASE_NAME }}" --progress=none
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto-remediation by OpenText SAST Aviator'
          branch: aviator/audit-remediate-${{github.run_id}}
          delete-branch: true
          title: 'Remediation of security issues detected by OpenText SAST'
          body: |
            Remediation of security issues detected by OpenText SAST.
            This PR was automatically created by OpenText SAST Aviator.
            Platform: ${{ inputs.platform }}
            Target: ${{ inputs.platform == 'SSC' && format('{0}:{1}', env.SSC_APPLICATION_NAME, env.SSC_VERSION_NAME) || format('{0}:{1}', env.FOD_APPLICATION_NAME, env.FOD_RELEASE_NAME) }}
            Please review carefully before merging.